version: '3.9'
services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - ms-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    networks:
      - ms-network

  employee-service:
    build: ./employee-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
    networks:
      - ms-network

  societe-service:
    build: ./societe-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
    networks:
      - ms-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ms-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    networks:
      - ms-network

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: societe_db
    ports:
      - "3306:3306"
    networks:
      - ms-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - ms-network

networks:
  ms-network:
