version: '3.8'

services:

  discovery-server:
    image: discovery-server
    build: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    image: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  employee-service:
    image: employee-service
    build: ./employee-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - discovery-server
      - config-server
      - kafka

  societe-service:
    image: societe-service
    build: ./societe-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - discovery-server
      - config-server
      - kafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

networks:
  backend:
    driver: bridge